modLoader="javafml"
loaderVersion="[${fml_min},)"
license="GPL v3.0"
displayURL="https://www.curseforge.com/minecraft/mc-mods/terraincognita"
issueTrackerURL="https://github.com/Azmalent/terra-incognita/issues"

[[mods]]
modId="terraincognita"
version="${mod_version}"
displayName="${mod_name}"
logoFile="terraincognita.png"
authors="Azmalent"
description='''
An expansion mod focusing on nature and exploration.
'''

[[dependencies.terraincognita]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.terraincognita]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.terraincognita]]
    modId="cuneiform"
    mandatory=true
    versionRange="[${cuneiform_version},)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.terraincognita]]
    modId="terrablender"
    mandatory=true
    versionRange="[${terrablender_version},)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.terraincognita]]
    modId="jei"
    mandatory=false
    versionRange="[${jei_version},)"
    ordering="AFTER"
    side="CLIENT"

[[dependencies.terraincognita]]
    modId="quark"
    mandatory=false
    versionRange="[${quark_version},)"
    ordering="AFTER"
    side="BOTH"
