modLoader="javafml"
loaderVersion="[${fml_min},)"
license="GPL v3.0"

[[mods]]
modId="terraincognita"
version="${mod_version}"
displayName="${mod_name}"
logoFile="terraincognita.png"
authors="Azmalent"
description='''
An expansion focusing on nature and exploration.
'''

[[dependencies.terraincognita]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.terraincognita]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.terraincognita]]
    modId="cuneiform"
    mandatory=true
    versionRange="[${cuneiform_version},)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.terraincognita]]
    modId="jei"
    mandatory=false
    versionRange="[7.6.0,)"
    ordering="AFTER"
    side="CLIENT"

[[dependencies.terraincognita]]
    modId="quark"
    mandatory=false
    versionRange="[r2.4-312,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.terraincognita]]
    modId="buzzier_bees"
    mandatory=false
    versionRange="[3,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.terraincognita]]
    modId="upgrade_aquatic"
    mandatory=false
    versionRange="[3,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.terraincognita]]
    modId="farmersdelight"
    mandatory=false
    versionRange="[0.4,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.terraincognita]]
    modId="simplytea"
    mandatory=false
    versionRange="[2.4.0,)"
    ordering="AFTER"
    side="BOTH"
